# Generated by Django 5.2.11 on 2026-02-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatresponse_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=100)),
                ('keywords', models.TextField(help_text='Enter comma separated keywords')),
                ('response', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ChatResponse',
        ),
    ]
